services:
  app:
    build: .
    restart: always
    container_name: markitdown
    volumes:
      - .:/app
    ports:
      - "${OUTER_PORT}:${INNER_PORT}"
    environment:
      - EXIFTOOL_PATH=/usr/bin/exiftool
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - INNER_PORT=${INNER_PORT}
    # 动态使用环境变量中的内部端口
    command: ["sh", "-c", "uvicorn app.app:app --host 0.0.0.0 --port $INNER_PORT --reload"]